using System;
using System.Collections.Generic;
using MCWorlds.Commands;

namespace MCWorlds
{
    public abstract class Command
    {
        public abstract string name { get; }
        public abstract string shortcut { get; }
        public abstract string type { get; }
        public abstract bool museumUsable { get; }
        public abstract LevelPermission defaultRank { get; }
        public abstract void Use(Player p, string message);
        public abstract void Help(Player p, string message = "");

        public static CommandList all = new CommandList();
        public static CommandList core = new CommandList();
        public static void InitAll()
        {
            all.Add(new CmdAbort());
            all.Add(new CmdAbout());
            all.Add(new CmdAccept());
            all.Add(new CmdAfk());
            all.Add(new CmdAfktime());
            all.Add(new CmdAward());
            all.Add(new CmdAwards());
            all.Add(new CmdAwardMod());
            all.Add(new CmdBan());
            all.Add(new CmdBanip());
            all.Add(new CmdBienvenu());
            all.Add(new CmdBind());
            all.Add(new CmdBlocks());
            all.Add(new CmdBlockSet());
            all.Add(new CmdBomberman());
            all.Add(new CmdBotAdd());
            all.Add(new CmdBotAI());
            all.Add(new CmdBotRemove());
            all.Add(new CmdBots());
            all.Add(new CmdBotSet());
            all.Add(new CmdBotSummon());
            all.Add(new CmdBrush());
            all.Add(new CmdChangeName());
            all.Add(new CmdChangeSkin());
            all.Add(new CmdClearBlockChanges());
            all.Add(new CmdClick());
            all.Add(new CmdClones());
            all.Add(new CmdCmdBind());
            all.Add(new CmdCmdCreate());
            all.Add(new CmdCmdLoad());
            all.Add(new CmdCmdSet());
            all.Add(new CmdCmdUnload());
            all.Add(new CmdCompile());
            all.Add(new CmdCollone());
            all.Add(new CmdColor());
            all.Add(new CmdCopy());
            all.Add(new CmdCrashServer());
            //all.Add(new CmdCTF());
            all.Add(new CmdCTF2());
            all.Add(new CmdCuboid());
            all.Add(new CmdDelete());
            all.Add(new CmdDeleteLvl());
            all.Add(new CmdDemote());
            all.Add(new CmdDevs());
            all.Add(new CmdDislike());
            all.Add(new CmdDown());
            all.Add(new CmdDrill());
            all.Add(new CmdDrop());
            all.Add(new CmdEmote());
            all.Add(new CmdExamine());
            all.Add(new CmdExit());
            all.Add(new CmdFAQ());
            all.Add(new CmdFill());
            all.Add(new CmdFixGrass());
            all.Add(new CmdFlipHeads());
            all.Add(new CmdFly());
            all.Add(new CmdFollow());
            all.Add(new CmdFoot());
            all.Add(new CmdFreeze());
            all.Add(new CmdGame());
            all.Add(new CmdGamemode());
            all.Add(new CmdGive());
            all.Add(new CmdGoto());
            all.Add(new CmdGun());
            all.Add(new CmdHacks());
            all.Add(new CmdHasirc());
                    // all.Add(new CmdHeartbeat()); DEBUG COMMAND DO NOT USE
            all.Add(new CmdHelp());
            all.Add(new CmdHide());
            all.Add(new CmdHollow());
            all.Add(new CmdHome());
            all.Add(new CmdHost());
                    // all.Add(new Cmdif());
            all.Add(new CmdImageprint());
            all.Add(new CmdImpersonate());
            all.Add(new CmdImport());
            all.Add(new CmdInbox());
            all.Add(new CmdInfection());
            all.Add(new CmdInfo());
            all.Add(new CmdInvincible());
            all.Add(new CmdJail());
            all.Add(new CmdJoker());
            all.Add(new CmdJumpTo());
            all.Add(new CmdKick());
            all.Add(new CmdKickban());
            all.Add(new CmdKill());
            all.Add(new Cmdkillinv());
            all.Add(new CmdLastCmd());
            all.Add(new CmdLevels());
            all.Add(new CmdLike());
                    //all.Add(new CmdLikeReset());
            all.Add(new CmdLimit());
            all.Add(new CmdLine());
            all.Add(new CmdLmissile());
            all.Add(new CmdLoad());
            all.Add(new CmdLowlag());
            all.Add(new CmdLisse());
            all.Add(new CmdMain());
            all.Add(new CmdMap());
            all.Add(new CmdMapInfo());
            all.Add(new CmdMaptchat());
            all.Add(new CmdMask());
            all.Add(new CmdMe());
            all.Add(new CmdMeasure());
                //all.Add(new CmdMegaboid());
            all.Add(new CmdMessageBlock());
            all.Add(new CmdMissile());
            all.Add(new CmdMode());
            all.Add(new CmdModerate());
            all.Add(new CmdMove());
            all.Add(new CmdMuseum());
            all.Add(new CmdMute());
            all.Add(new CmdNewLvl());
            all.Add(new CmdNews());
            all.Add(new CmdNotes());
            all.Add(new CmdNuke());
            all.Add(new CmdNotes());
            all.Add(new CmdOpChat());
            all.Add(new CmdOutline());
            all.Add(new CmdPaint());
            all.Add(new CmdPaste());
            all.Add(new CmdPause());
            all.Add(new CmdPay());
            all.Add(new CmdPCount());
            all.Add(new CmdPermissionBuild());
            all.Add(new CmdPergun());
            all.Add(new CmdPermissionVisit());
            all.Add(new CmdPhysics());
            all.Add(new CmdPiston());
            all.Add(new CmdPlace());
            all.Add(new CmdPlayers());
            all.Add(new CmdPortal());
            all.Add(new CmdPosition());
            all.Add(new CmdPossess());
            all.Add(new CmdPromote());
            all.Add(new CmdPTeleport());
            all.Add(new CmdPyramide());
            all.Add(new CmdRainbow());
            all.Add(new CmdRedo());
            all.Add(new CmdRedstone());
            all.Add(new CmdRenameLvl());
            all.Add(new CmdRepeat());
            all.Add(new CmdReplace());
            all.Add(new CmdReplaceAll());
            all.Add(new CmdReplaceNot());
            all.Add(new CmdResetBot());
            all.Add(new CmdResetLvl());
            all.Add(new CmdRestart());
            all.Add(new CmdRestartPhysics());
            all.Add(new CmdRestore());
            all.Add(new CmdRetrieve());
            all.Add(new CmdReveal());
            all.Add(new CmdRide());
            all.Add(new CmdRoll());
            all.Add(new CmdRules());
            all.Add(new CmdSalon());
            all.Add(new CmdSave());
            all.Add(new CmdSavePoint());
            all.Add(new CmdSavePoint2());
            all.Add(new CmdSay());
                    //all.Add(new CmdScript());
            all.Add(new CmdSend());
            all.Add(new CmdServerReport());
            all.Add(new CmdSetMaxMaps());
            all.Add(new CmdSetRank());
            all.Add(new CmdSetspawn());
            all.Add(new CmdSkill());
            all.Add(new CmdSlap());
            all.Add(new CmdSpawn());
            all.Add(new CmdSphereCentre());
            all.Add(new CmdSpheroid());
            all.Add(new CmdSpin());
            all.Add(new CmdStairs());
            all.Add(new CmdStatic());
            all.Add(new CmdStats());
            all.Add(new CmdStopServer());
            all.Add(new CmdStore());
            all.Add(new CmdSummon());
            all.Add(new CmdTake());
            all.Add(new CmdTColor());
            all.Add(new CmdTeam());
            all.Add(new CmdTempBan());
            all.Add(new CmdText());
            all.Add(new CmdTime());
                    //all.Add(new CmdTimer());
            all.Add(new CmdTitle());
            all.Add(new CmdTnt());
            all.Add(new CmdTp());
            all.Add(new CmdTree());
            all.Add(new CmdTrust());
            all.Add(new CmdUnban());
            all.Add(new CmdUnbanip());
            all.Add(new CmdUndo());
            all.Add(new CmdUnflood());
            all.Add(new CmdUnload());
            all.Add(new CmdUp());
            all.Add(new CmdView());
            all.Add(new CmdViewRanks());
            all.Add(new CmdVips());
            all.Add(new CmdVoice());
            all.Add(new CmdWhisper());
            if (Server.useWhitelist) { all.Add(new CmdWhitelist()); }
            all.Add(new CmdWhoip());
            all.Add(new CmdWhois());
            all.Add(new CmdWhowas());
            all.Add(new CmdWorld());
            all.Add(new CmdWorlds());
            all.Add(new CmdWrite());
            all.Add(new CmdXban());
            all.Add(new CmdZombieattaque());

            core.commands = new List<Command>(all.commands);

            Scripting.Autoload();
        }
    }
}